name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

env:
  VM_IP: ${{ secrets.VM_IP }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  USER: ${{ secrets.USER }}
  PROJECT_DIR: "/home/${{ secrets.SSH_USERNAME }}/my-next-app"
  WORKING_DIR: "client"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run lint
        run: npm run lint
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build project
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}

      - name: Setup SSH
        run: |
          echo "$SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          mkdir -p ~/.ssh
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to VM
        run: |
          scp -i ssh_key.pem -r ${{ env.WORKING_DIR }}/* $SSH_USERNAME@$VM_IP:$PROJECT_DIR
          ssh -i ssh_key.pem $SSH_USERNAME@$VM_IP << 'EOF'
            cd $PROJECT_DIR
            npm install
            npm run build
            pm2 restart dtect || pm2 start npm --name "dtect" -- run start
          EOF

      - name: Cleanup
        run: rm -f ssh_key.pem
